### ISSUE TITLE
Bonding/pairing with devices

### ISSUE THREAD

**Issue by ihors0** [nexussays/ble.net#14]
How i can paid with device using pairing code?

**Comment by nexussays** [comment]
Unfortunately I don't as yet have any BLE devices that use pairing/bonding to test against, so I haven't implemented it in the API.

I'll update this issue when there are updates.

**Comment by nexussays** [comment]
Hey @ihors0 there doesn't seem to be anything additional needed to do to pair/bond, it looks like each OS handles it internally. E.g., on Android you get a notification to pair when trying to connect to a device using the BLE.net `ConnectToDevice` method.

If you are still having issues, let me know and I can try to look into it further.

**Comment by EmJay1171** [comment]
How can I pair the devices? Is this possible?
