### ISSUE TITLE
Outdated documentation with non-existent methods

### ISSUE THREAD

**Issue by aliuspetraska** [nexussays/ble.net#15]
Hi,

It seems after latest updates you forgot to update documentation and it seems that most of it is outdated;

For example according to http://dotnetapis.com/pkg/ble.net/0.12.14/win8/doc/nexus.protocols.ble.IBluetoothLowEnergyAdapter there are no method as ```.ScanForDevices```

Can you update documentation with an example how to use functionality for searching devices all around?

**Comment by nexussays** [comment]
Oof, sorry, that was an oversight on my part. Readme has been updated. I think that is the only change I missed, everything else looks correct.

Thanks for catching that!
