### ISSUE TITLE
UpdateDisplayedValue

### ISSUE THREAD

**Issue by foxble** [nexussays/ble.net#17]
Which device are you using to verify that ValueAsHex and ValueAsString are coming across correctly after clicking Read?
For SensorTag I'm getting, HEX 00000000, UTF8 blank,
<img src="https://user-images.githubusercontent.com/31827501/33142730-4f61cb7c-cf6c-11e7-8873-a6c56f5127ec.png" width="25%" height="25%">

but I'm also getting these same values using nrf connect, hence which device was used for testing.
(UpdateDisplayedValue() is at line 233, https://github.com/nexussays/ble.net/blob/master/src/ble.net.sampleapp/viewmodel/BleGattCharacteristicViewModel.cs
-thank-you

**Comment by nexussays** [comment]
That is the expected value if the temperature sensor is off. You should search for the documentation of the SensorTag so you know what to expect; but specifically, the temperature service needs to be turned on by writing `1` to the on/off characteristic, then you can read the temperature value.

**Comment by foxble** [comment]
On/Off for aa02, easy enough, ...thank-you.

For aa01, I'm getting hex 2409400b, and utf8 "$ @".
<img src="https://user-images.githubusercontent.com/31827501/33188223-09eacdbe-d04d-11e7-98c2-81708654b6e1.png" width="25%" height="25%">

I'm not understanding the hex value of 0x2409400b and how it could be something like 21.95C.
A properly converted utf8 might give a clue.
If the hex was 0x155f, 2 bytes, then maybe I could get 21.95. 
But what is 2409?

(I noticed that on read, 400b keeps repeating and the first 4 characters change).

-thank-you

**Comment by nexussays** [comment]
See the SensorTag docs for how to convert the temperature data to a readable format http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#IR_Temperature_Sensor

**Comment by foxble** [comment]
that was it, ....thank-you
<img src="https://user-images.githubusercontent.com/31827501/33236263-328e7f42-d203-11e7-9d3d-d6b3750a5c46.png" width="25%" height="25%">

**Comment by nexussays** [comment]
:+1: good luck
