### ISSUE TITLE
Continuous Scanning of BLE devices

### ISSUE THREAD

**Issue by AbhijeetChowdhury** [nexussays/ble.net#18]
@nexussays ,

Is it possible to scan ble devices continuously without any scan timeout?

One way to achieve this is by putting the adapter.ScanForBroadcasts method inside a Device.Timer action. Is there any other way to achieve this?

**Comment by nexussays** [comment]
The interface for scan takes a CancellationToken so you can run it as long as you'd like. The methods taking a TimeSpan are extension methods on that interface.

Keep in mind though sometimes (especially on Android) devices stop being reported after extensive scans, so you may need to stop and restart the scan anyway.

**Comment by AbhijeetChowdhury** [comment]
@nexussays ,

Thanks for the suggestion. :)

**Comment by nexussays** [comment]
:+1:
