### ISSUE TITLE
Question regarding EnabledDisabledState.Unknown;

### ISSUE THREAD

**Issue by callon22** [nexussays/ble.net#28]
Hi!

Regarding `bleAdapter.CurrentState.Value == EnabledDisabledState.Unknown;` What does this state indicate?
I can see that in your test-project you see this as if the ble adapter was enabled? 

Best Regards
Niklas

**Comment by nexussays** [comment]
It means the state of the adapter is unknown :)

I don't think you should ever see this on Android or iOS but the UWP version is still a work in progress. As far as the sample app, if it's not able to detect the state of the adapter (i.e. `EnabledDisabledState.Unknown`) it just assumes it's enabled.

**Comment by callon22** [comment]
@nexussays  Thanks!! =)

**Comment by nexussays** [comment]
:+1:
