### ISSUE TITLE
Package in Nuget not compatible with .NETPortable, Version v4.5, Profile=Profile 111

### ISSUE THREAD

**Issue by nicodwi** [nexussays/ble.net#30]
Hello Nexussays,

Is there any package or maybe update for .Net Version 4.5 ?
I can't install it from the nuget.
I already try to update from your github to v.4.5, but it always failed.
I'm a newbie in xamarin, but i really need this plugin for BLE project.

Thx

**Comment by nexussays** [comment]
Profile111 includes Windows Phone 8 which ble.net does not support. Change to Profile7 which only supports .Net 4.5 and Windows 8 (and which is what [ble.net targets](https://github.com/nexussays/ble.net/blob/master/src/ble.net/ble.net.csproj#L16)). Let me know if you're still having issues after that.
