### ISSUE TITLE
NSBluetoothPeripheralUsageDescription

### ISSUE THREAD

**Issue by callon22** [nexussays/ble.net#33]
Question:

Do you need to add this in info.plist file for iOS? I have not been using it and never go any problems? If i use it, when does the user get the question and how do you check the answer (if no i guess you need to handle it)? 

<key>NSBluetoothPeripheralUsageDescription</key>
<string>[MyAppNameHere] would like to use bluetooth.</string>

**Comment by nexussays** [comment]
`NSBluetoothPeripheralUsageDescription` is required to be present in iOS 10.0+ or your app will be rejected from the store. But I believe it is only used if you are running bluetooth in the background.

I'll update the readme to be more clear.

See Apple's docs for more info https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW20

**Comment by callon22** [comment]
Thanks!
