### ISSUE TITLE
Rssi measurement

### ISSUE THREAD

**Issue by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [nexussays/ble.net#34]
In [IBlePeripheral.cs](https://github.com/nexussays/ble.net/blob/master/src/ble.net/scan/IBlePeripheral.cs) you mention RSSI is measured in decibels (dB). Is this true? or is it measured in dBm?

>  /// Received signal strenth indicator, in decibels

**Comment by nexussays** [comment]
D'oh, yes that should be decibel-milliwatts, I will update the doc comments for the next release. Thanks for catching that!
