### ISSUE TITLE
Help compiling against Profile111

### ISSUE THREAD

**Issue by nicodwi** [nexussays/ble.net#36]
Hi,

Can you update the source so can compatible with .netVersion4.5 ?
I already use your github or from nuget, but it still can't work in .netVersion 4.5

Or, can you tell me which one that should i modified for the upgrade.

Thx

**Comment by nexussays** [comment]
The core library is compatible with .NET 4.5, it is compiled as a Profile7 PCL. What issues are you having?

**Comment by nicodwi** [comment]
i need to compatible with profile 111

**Comment by nexussays** [comment]
You need Windows Phone 8.1 support?

**Comment by nicodwi** [comment]
it's done. i'm using your github dll, not downloading from nuget.
