### ISSUE TITLE
Disconnection Notification

### ISSUE THREAD

**Issue by johnnyb** [nexussays/ble.net#48]
Is there a way to detect when the device itself disconnects?  I couldn't find a callback or anything, but could have missed it.

**Comment by nexussays** [comment]
https://github.com/nexussays/ble.net/blob/27c89f0b88b355cfba75eb307fca4f79f4a55f45/src/ble.net/IBleGattServerConnection.cs#L83-L86


I will update the readme to call that out specifically.
