### ISSUE TITLE
iOS: Read results in notification

### ISSUE THREAD

**Issue by callon22** [nexussays/ble.net#50]
Hi!

I have a problem with iOS. If i activate notification for a characteristic and then do a read on the same, it will result in a notification? This behavior only happens on iOS? Evry read i do will lead to a notification, even if the value is not changed.

Let me now if you need some more information but i guess its easy to recreate for you

**Comment by nexussays** [comment]
The iOS API unfortunately doesn't distinguish between a read and a notify when listening for the event. I tried to implement something to detect it, but it didn't work, so unfortunately this is a won't fix until Apple fixes their API, sorry :(
