### ISSUE TITLE
read characteristic value is not working but write & notify works?

### ISSUE THREAD

**Issue by aloksharma1** [nexussays/ble.net#52]
hi,

i am having a weird issue with my HMSoft Ble Device, i can see data on receiving end by using gattServer.WriteCharacteristicValue(service_guid.Value, char_guid.Value);

but the gattServer.ReadCharacteristicValue(service_guid.Value, char_guid.Value); gives me a static value, while notifier on same GUID are giving new values.

var notifier = gattServer.NotifyCharacteristicValue(
                       service_guid.Value,
                       char_guid.Value,
                       bytes => {
                           readValue = bytes.AsUtf8String();
                           //var txtLogs = FindViewById<EditText>(Resource.Id.txtLogs);
                           txtLogs.Text += $"current notifier result: {readValue} {System.Environment.NewLine}";
                       });

**Comment by nexussays** [comment]
iOS or Android?

**Comment by nexussays** [comment]
Closing because I'm unable to replicate. Feel free to re-open with repro steps!
