### ISSUE TITLE
ReadDescriptorValue throws Exception which cannot be handled

### ISSUE THREAD

**Issue by devopsone** [nexussays/ble.net#57]
Hi,
thanks for the project. It works really well. I'm just having trouble using ReadDescriptorValue() as it throws an Unhandled Exception (Android) which cannot be catched (even using await): 

System.NullReferenceException: Object reference not set to an instance of an object.

with iOS it can be catched and throws an 

System.ArgumentNullException: Value cannot be null.Parameter name: descriptor  at CoreBluetooth.CBPeripheral.ReadValue (CoreBluetooth.CBDescriptor descriptor) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/CoreBluetooth/CBPeripheral.g.cs:194

Anyway it seems ReadDescriptorValue() is broken as its also commented out in the sample app.

//await vm.UpdateDescriptors();

Any info on this? Thanks

**Comment by nexussays** [comment]
Thanks for the report! Will be fixed in `1.1.0`. Also added integration tests for descriptors to ensure it doesn't regress.
