### ISSUE TITLE
System.IO.InvalidDataException during ScanForBroadcasts

### ISSUE THREAD

**Issue by 6Demon** [nexussays/ble.net#62]
Hi,
If device recieves adv that cant parse it throws unhandeled System.IO.InvalidDataException and breaks the scan.

**Comment by nexussays** [comment]
Thanks for the report! Do you have an example of such an advertisement? Or if there is a specific device than reliably broadcasts it, maybe I can repro?

**Comment by 6Demon** [comment]
My assumtion its following raw data:               
 0x02 ,0x01 ,0x1a ,0x1b ,0xff ,0x75 ,0x00 ,0x42 ,0x04 ,0x01 ,0x01 ,0x4f ,0x5c ,
0x49 ,0x7d ,0x95 ,0x4b ,0xa9 ,0x5e ,0x49 ,0x7d ,0x17 ,0x4b ,0xa8 ,0x2c ,0xf4 ,0x00,
0x00 ,0x00 ,0x00 ,0x00 ,0x02 ,0x0a ,0x09 ,0x1b ,0x08 ,0x5b ,0x54 ,0x56 ,0x5d ,0x20,
0x53 ,0x61 ,0x6d ,0x73 ,0x75 ,0x6e ,0x67 ,0x20 ,0x35 ,0x20 ,0x53 ,0x65 ,0x72 ,0x69,
0x65 ,0x73 ,0x20 ,0x28 ,0x34 ,0x39 ,0x29

It seems that it it some Samsung device that sends the data. Regardless the interuption in scan is pretty breaking.

**Comment by nexussays** [comment]
Cheers, thanks. I've never seen that before. I'll try to repro.

**Comment by 6Demon** [comment]
I think that the BleAdvertisingUtils.ParseAdvertisingPayloadData breaks the scan with invalid payload

**Comment by 6Demon** [comment]
Can confirm that issue is coming from Samsun TV. if you need can provide more raw data

**Comment by nexussays** [comment]
Will go out in next release. Thanks for providing the sample data!
