### ISSUE TITLE
Roadmap on Windows support?

### ISSUE THREAD

**Issue by tdoneal** [nexussays/ble.net#7]
@nexussays This library looks very promising, but I need it for Windows.  Do you plan on digging into the "incredibly obtuse" APIs for Win10 BLE support at any point in the near future?

**Comment by nexussays** [comment]
Unfortunately I am quite swamped with other work for the next couple months and don't expect that I will make any progress on Win10 BLE support in that time. Sorry 😞

**Comment by BradfordMedeiros** [comment]
seconded for BLE support! this feature is very important to me!

**Comment by nexussays** [comment]
Closing in favor for #37 #38  #39
